# Generated by Django 5.2 on 2025-04-28 04:05

import djangojokes.storage_backends
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Image must be 200px by 200px.', storage=djangojokes.storage_backends.PublicMediaStorage(), upload_to='avatars/', validators=[users.models.validate_avatar]),
        ),
    ]
