# Generated by Django 5.2 on 2025-04-13 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aplicant',
            new_name='Applicant',
        ),
    ]
