# Generated by Django 5.2 on 2025-04-23 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_applicant_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='desirely_hourly_wage',
            new_name='desired_hourly_wage',
        ),
    ]
