# Generated by Django 5.2 on 2025-04-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_rename_desirely_hourly_wage_applicant_desired_hourly_wage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='available_days',
            field=models.CharField(max_length=50),
        ),
    ]
